# Generated by Django 5.1.1 on 2024-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(upload_to='', verbose_name='Profile Photo'),
        ),
    ]
